import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { X, Sparkles, Loader2, Check, Trash2, Map } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

interface AISiteGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (data: any) => void;
  initialUrl?: string;
}

export function AISiteGeneratorModal({ isOpen, onClose, onSave, initialUrl }: AISiteGeneratorModalProps) {
  const { token } = useAuth();
  const [url, setUrl] = useState("");
  const [isProcessing, setIsProcessing] = useState(false);
  const [aiResult, setAiResult] = useState<any>(null);
  const [debugLog, setDebugLog] = useState<string[]>([]);
  const [error, setError] = useState("");
  const autoGeneratedRef = useRef(false);

  const addLog = (msg: string) => {
    setDebugLog(prev => [...prev, `${new Date().toLocaleTimeString('en-AU')}: ${msg}`]);
  };

  const handleGenerate = async (overrideUrl?: string) => {
    const targetUrl = overrideUrl || url;
    if (!targetUrl) return;
    
    setIsProcessing(true);
    setDebugLog([]);
    setError("");
    addLog(`Starting generation for: ${targetUrl}`);
    try {
      addLog("Sending POST request to /api/ai/generate...");
      const res = await fetch("/api/ai/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ url: targetUrl }),
      });
      
      addLog(`Response status: ${res.status}`);
      const contentType = res.headers.get("content-type");
      addLog(`Content-Type: ${contentType}`);
      
      if (!contentType || !contentType.includes("application/json")) {
        const text = await res.text();
        addLog(`Error body: ${text.slice(0, 100)}`);
        throw new Error(`Server error (${res.status}): ${text.slice(0, 200) || 'Empty response'}`);
      }

      const data = await res.json();
      addLog("JSON parsed successfully");
      
      if (!res.ok) {
        throw new Error(data.error || "Generation failed");
      }
      
      setAiResult(data);
      addLog("Generation complete!");
    } catch (e: any) {
      console.error(e);
      addLog(`ERROR: ${e.message}`);
      setError(e.message || "Generation failed");
    } finally {
      setIsProcessing(false);
    }
  };

  useEffect(() => {
    if (isOpen) {
      if (initialUrl && !autoGeneratedRef.current) {
        autoGeneratedRef.current = true;
        setUrl(initialUrl);
        handleGenerate(initialUrl);
      } else if (!initialUrl) {
        setUrl("");
        setAiResult(null);
        setDebugLog([]);
      }
    } else {
      autoGeneratedRef.current = false;
    }
  }, [isOpen, initialUrl]);

  const handleDiscard = () => {
    setAiResult(null);
    setUrl("");
    onClose();
  };

  const handleConfirmSave = async () => {
    if (!aiResult) return;
    
    let siteguideVersion = "";
    try {
      const token = localStorage.getItem("adminToken");
      const vRes = await fetch("/api/sites/siteguide-version", {
        headers: { Authorization: `Bearer ${token}` },
      });
      const vData = await vRes.json();
      if (vData.version) siteguideVersion = vData.version;
    } catch {}

    const mappedData = {
      name: aiResult.name || "",
      type: (aiResult.type || "").toLowerCase().includes("inland") ? "Inland" : "Coastal",
      pgRating: aiResult.pgRating || "",
      hgRating: aiResult.hgRating || "",
      windDir: aiResult.windDir || "",
      windSpeed: aiResult.windSpeed || "",
      lat: aiResult.lat ? String(aiResult.lat) : "",
      lon: aiResult.lon ? String(aiResult.lon) : "",
      description: aiResult.siteOverview || "",
      launch: aiResult.launchArea || "",
      landing: aiResult.landingZones || "",
      hazards: (aiResult.knownHazards || []).join('\n'),
      rules: (aiResult.siteRules || []).join('\n'),
      siteContact: aiResult.siteContact || "",
      siteContactPhone: aiResult.siteContactPhone || "",
      navigateTo: aiResult.navigateTo || "",
      launchHeight: aiResult.launchHeight || "",
      hoodedPloversLink: aiResult.hoodedPloversLink || "",
      emergencyMarker: aiResult.emergencyMarker || "",
      what3words: aiResult.what3words || "",
      status: aiResult._isSiteClosed ? "closed" : aiResult._isRestricted ? "restricted" : "open",
      isSkyHighSite: (aiResult.responsibleClub && /sky\s*high/i.test(aiResult.responsibleClub)) ? "true" : "false",
      _essentialImages: aiResult._essentialImages || [],
      _essentialText: aiResult._essentialText || "",
      _unassignedText: aiResult.unassignedText || "",
      siteguideVersion: siteguideVersion,
      siteguideScrapedAt: new Date().toISOString(),
    };
    
    onSave(mappedData);
    handleDiscard();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-card rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        <div className="p-6 border-b flex justify-between items-center bg-navy text-white">
          <div className="flex items-center gap-2">
            <Sparkles className="w-6 h-6 text-sky-light" />
            <h2 className="text-xl font-bold">Scrape Site Guide</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-lg transition-colors">
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          {!aiResult ? (
            (isProcessing || initialUrl) ? (
              <div className="max-w-xl mx-auto py-12 text-center space-y-6">
                <div className="space-y-4 flex flex-col items-center justify-center h-full">
                   <Loader2 className="w-16 h-16 text-sky animate-spin mb-4" />
                   <h3 className="text-2xl font-bold text-navy">Processing Site Content</h3>
                   <p className="text-muted-foreground max-w-md">
                     Extracting and analyzing details from <br/>
                     <span className="font-mono text-xs bg-muted px-2 py-1 rounded mt-1 inline-block text-sky-600 truncate max-w-full">
                       {url || initialUrl || "provided URL"}
                     </span>
                   </p>
                   
                   {error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">{error}</div>}

                   {debugLog.length > 0 && (
                      <div className="mt-8 w-full p-4 bg-gray-900 text-green-400 font-mono text-[10px] rounded-xl text-left max-h-[200px] overflow-y-auto shadow-inner">
                        {debugLog.map((log, i) => (
                          <div key={i} className="border-b border-white/5 last:border-0 py-1">{log}</div>
                        ))}
                      </div>
                    )}
                </div>
              </div>
            ) : (
            <div className="max-w-xl mx-auto py-12 text-center space-y-6">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold text-navy">Generate Site from URL</h3>
                <p className="text-muted-foreground">Paste a link to a site guide (e.g. from SAFA or VHPA) and Smart extraction will capture and re-paraphrase the details for you.</p>
              </div>
              
              {error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">{error}</div>}

              <div className="space-y-4">
                <input 
                  type="url" 
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  placeholder="https://siteguide.org.au/Sites/..."
                  className="w-full p-4 border-2 border-border-faint rounded-xl focus:border-sky focus:ring-0 text-lg transition-all"
                  disabled={isProcessing}
                />
                <Button 
                  onClick={() => handleGenerate()} 
                  disabled={isProcessing || !url}
                  className="w-full py-6 text-lg bg-sky hover:bg-sky-light text-white rounded-xl shadow-lg shadow-sky/20 transition-all"
                >
                  <Sparkles className="w-5 h-5 mr-2" />
                  Generate Site Content
                </Button>
              </div>
              
              <div className="pt-8 grid grid-cols-3 gap-4 text-xs text-foreground-faint">
                <div className="p-3 border rounded-lg">
                  <div className="font-bold text-navy mb-1">1. Scrape</div>
                  Extracts raw text from the provided URL
                </div>
                <div className="p-3 border rounded-lg">
                  <div className="font-bold text-navy mb-1">2. Process</div>
                  Gemini categorizes and paraphrases content
                </div>
                <div className="p-3 border rounded-lg">
                  <div className="font-bold text-navy mb-1">3. Review</div>
                  Check and edit before saving to database
                </div>
              </div>
            </div>
            )
          ) : (
            <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
              <div className="bg-sky/5 p-4 rounded-xl border border-sky/20 flex items-center justify-between">
                <div>
                  <h3 className="font-bold text-navy">Smart Generation Complete</h3>
                  <p className="text-sm text-foreground-secondary">Review the extracted and paraphrased content below.</p>
                </div>
                
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-6">
                  <section>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">Site Metadata</h4>
                    <div className="grid grid-cols-2 gap-4 bg-background p-4 rounded-xl border">
                      <div>
                        <div className="text-[10px] text-foreground-faint uppercase">Name</div>
                        <div className="font-medium text-navy">{aiResult.name}</div>
                      </div>
                      <div>
                        <div className="text-[10px] text-foreground-faint uppercase">Type</div>
                        <div className="font-medium text-navy">{aiResult.type}</div>
                      </div>
                      <div>
                        <div className="text-[10px] text-foreground-faint uppercase">PG Rating</div>
                        <div className="font-medium text-navy text-xs">{aiResult.pgRating || "—"}</div>
                      </div>
                      <div>
                        <div className="text-[10px] text-foreground-faint uppercase">HG Rating</div>
                        <div className="font-medium text-navy text-xs">{aiResult.hgRating || "—"}</div>
                      </div>
                      <div>
                        <div className="text-[10px] text-foreground-faint uppercase">Wind</div>
                        <div className="font-medium text-navy">{aiResult.windDir}</div>
                      </div>
                      <div>
                        <div className="text-[10px] text-foreground-faint uppercase">Coordinates</div>
                        <div className="font-medium text-navy">{Number(aiResult.lat)?.toFixed(4)}, {Number(aiResult.lon)?.toFixed(4)}</div>
                      </div>
                    </div>
                  </section>

                  <section>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">Site Overview</h4>
                    <textarea 
                      value={aiResult.siteOverview}
                      onChange={(e) => setAiResult({...aiResult, siteOverview: e.target.value})}
                      className="w-full p-4 rounded-xl border shadow-sm text-sm text-foreground-label min-h-[150px] focus:ring-sky focus:border-sky"
                    />
                  </section>

                  <section>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">Additional Details</h4>
                    <div className="space-y-3 bg-background p-4 rounded-xl border">
                      <div className="grid grid-cols-2 gap-3">
                        <div>
                          <label className="text-[10px] text-foreground-faint uppercase font-bold">Contact Name</label>
                          <input 
                            value={aiResult.siteContact || ""}
                            onChange={(e) => setAiResult({...aiResult, siteContact: e.target.value})}
                            className="w-full p-2 text-sm border rounded"
                          />
                        </div>
                        <div>
                          <label className="text-[10px] text-foreground-faint uppercase font-bold">Contact Phone</label>
                          <input 
                            value={aiResult.siteContactPhone || ""}
                            onChange={(e) => setAiResult({...aiResult, siteContactPhone: e.target.value})}
                            className="w-full p-2 text-sm border rounded"
                          />
                        </div>
                        <div>
                          <label className="text-[10px] text-foreground-faint uppercase font-bold">Responsible Club</label>
                          <div className="flex items-center gap-2">
                            <input 
                              value={aiResult.responsibleClub || ""}
                              onChange={(e) => setAiResult({...aiResult, responsibleClub: e.target.value})}
                              className="w-full p-2 text-sm border rounded"
                            />
                            {aiResult.responsibleClub && /sky\s*high/i.test(aiResult.responsibleClub) && (
                              <span className="text-xs bg-emerald-100 text-emerald-700 px-2 py-1 rounded-full whitespace-nowrap font-medium">Club Site</span>
                            )}
                          </div>
                        </div>
                        <div>
                          <label className="text-[10px] text-foreground-faint uppercase font-bold">Launch Height</label>
                          <input 
                            value={aiResult.launchHeight || ""}
                            onChange={(e) => setAiResult({...aiResult, launchHeight: e.target.value})}
                            className="w-full p-2 text-sm border rounded"
                          />
                        </div>
                        <div>
                          <label className="text-[10px] text-foreground-faint uppercase font-bold">Emergency Marker</label>
                          <input 
                            value={aiResult.emergencyMarker || ""}
                            onChange={(e) => setAiResult({...aiResult, emergencyMarker: e.target.value})}
                            className="w-full p-2 text-sm border rounded"
                          />
                        </div>
                        <div className="col-span-2">
                          <label className="text-[10px] text-foreground-faint uppercase font-bold">Navigate To Link</label>
                          <input 
                            value={aiResult.navigateTo || ""}
                            onChange={(e) => setAiResult({...aiResult, navigateTo: e.target.value})}
                            className="w-full p-2 text-sm border rounded"
                          />
                        </div>
                        <div className="col-span-2">
                          <label className="text-[10px] text-foreground-faint uppercase font-bold">What3Words</label>
                          <input 
                            value={aiResult.what3words || ""}
                            onChange={(e) => setAiResult({...aiResult, what3words: e.target.value})}
                            className="w-full p-2 text-sm border rounded"
                          />
                        </div>
                      </div>
                    </div>
                  </section>
                </div>

                <div className="space-y-6">
                  <section>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">Known Hazards (One per line)</h4>
                    <textarea 
                      value={aiResult.knownHazards?.join('\n')}
                      onChange={(e) => setAiResult({...aiResult, knownHazards: e.target.value.split('\n')})}
                      className="w-full p-4 rounded-xl border shadow-sm text-sm text-foreground-label min-h-[100px] focus:ring-sky focus:border-sky"
                    />
                  </section>

                  <section>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">Site Rules (One per line)</h4>
                    <textarea 
                      value={aiResult.siteRules?.join('\n')}
                      onChange={(e) => setAiResult({...aiResult, siteRules: e.target.value.split('\n')})}
                      className="w-full p-4 rounded-xl border shadow-sm text-sm text-foreground-label min-h-[100px] focus:ring-sky focus:border-sky"
                    />
                  </section>

                  <section>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">Launch Area</h4>
                    <textarea 
                      value={aiResult.launchArea}
                      onChange={(e) => setAiResult({...aiResult, launchArea: e.target.value})}
                      className="w-full p-4 rounded-xl border shadow-sm text-sm text-foreground-label min-h-[100px] focus:ring-sky focus:border-sky"
                    />
                  </section>

                  <section>
                    <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">Landing Zones</h4>
                    <textarea 
                      value={aiResult.landingZones}
                      onChange={(e) => setAiResult({...aiResult, landingZones: e.target.value})}
                      className="w-full p-4 rounded-xl border shadow-sm text-sm text-foreground-label min-h-[100px] focus:ring-sky focus:border-sky"
                    />
                  </section>

                  {aiResult._essentialImages && aiResult._essentialImages.length > 0 && (
                    <section>
                      <h4 className="text-xs font-bold uppercase tracking-wider text-foreground-faint mb-2">
                        <Map className="w-3 h-3 inline mr-1" />
                        Site Maps ({aiResult._essentialImages.length} found)
                      </h4>
                      <div className="flex gap-2 flex-wrap bg-background p-3 rounded-xl border">
                        {aiResult._essentialImages.map((img: string, i: number) => (
                          <img key={i} src={img} alt={`Site map ${i + 1}`} className="h-20 rounded border border-border object-contain bg-card" />
                        ))}
                      </div>
                    </section>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>

        {aiResult && (
          <div className="p-4 border-t bg-background flex justify-end gap-3">
            <Button variant="outline" onClick={handleDiscard}>Discard</Button>
            <Button onClick={handleConfirmSave} className="bg-emerald-500 hover:bg-emerald-600 text-white">
              <Check className="w-4 h-4 mr-2" /> Apply
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
