-- Migration 014: Populate site banners with random images from library
-- Assigns each site a pseudo-random banner image based on its type (coastal/inland)

-- For SQLite compatibility, this migration is kept simple.
-- The actual population happens via app startup code in db.ts or via
-- the TypeScript migration in server/migrations/053_populate_site_banners.ts
--
-- If you need to manually populate banners in PostgreSQL, use:
--   npx tsx scripts/populate-site-banners.ts
--
-- This is intentionally a no-op SQL file to avoid migration failures
-- while the app code handles the actual population logic.
