/**
 * GENERATED FILE — DO NOT EDIT. Run `npm run bake:landmask` to regenerate.
 *
 * Land and coverage masks for the thermal overlay, baked from GEODATA COAST
 * 100K 2004 (Geoscience Australia, CC BY 4.0) by scripts/bake-land-mask.mjs.
 * That script's header explains why the mask exists and how it is built.
 *
 * Two masks, because the two consumers ask different questions:
 *
 *   isOnLand   — exact coastline at Mean High Water. The client clips rendered
 *                pixels with this; it is what draws the visible coastline,
 *                because interpolateSpatial is a relaxed bilinear that bleeds
 *                ~10 km offshore from the nearest land point.
 *   isCovered  — the same mask dilated by 0.2° of true distance. The server
 *                chooses which lattice points to fetch with this, so a coastal
 *                site still has grid neighbours on its seaward side.
 *
 * Both replace hand-traced polygon rings that had drifted apart — the client
 * copy was tracing the *Victorian state border*, erasing ten columns of South
 * Australia and seven of the NSW far south coast that the server had already
 * fetched and stored. One generated artifact makes that class of drift
 * impossible.
 */

/** Mask extent and cell size, in degrees. */
export const MASK_BOUNDS = {
  lonMin: 139,
  lonMax: 151.5,
  latMin: -44,
  latMax: -33,
  res: 0.01,
} as const;

export const MASK_WIDTH = 1250;
export const MASK_HEIGHT = 1100;

/** Offshore buffer baked into the coverage mask, in degrees of latitude. */
export const COVERAGE_BUFFER_DEG = 0.2;

// Run-length encoded, LEB128 varints, MSB-first bit order, starting with a
// water run. ~6 KB each — small enough to inline rather than fetch, which
// keeps the masks synchronous and avoids a load-order hazard on first paint.
const LAND_RLE =
  "AIvzAgHgCQLgCQLgCQLeCQTdCQXdCQXcCQbdCQXcCQbcCQbdCQXbCQe/CQEBARkHvwkCAQEBAQIBEgi+CQMBAQEECAIFAQEJ" +
  "vgkBBAYGAwIOxQkEBgMBD8cJAgICAhPGCQMBGMgJBAIUyAkDBAEBEcUJBQQUxQkBBwMCEM4JFMwJBAIQywkEAhHNCQICEcsJ" +
  "AQEBAhLQCRLQCRLPCRPPCRPPCRPOCRTOCRTOCRTPCRPOCRTOCRTNCRXNCRXNCRXLCQECFMkJBAEUyQkBARfKCRjGCQIBAwEV" +
  "xQkGAhXHCQIBAQEWzAkWzAkWywkXywkXywkXygkYygkYygkYwAkEBhi/CQYEGb8JBgUYvwkIAhm/CQkBGb0JAwEFARu9CQEC" +
  "AQEBBBu9CQIIG74JAQMBAxzACSLACSK+CQEBIr0JJcEJIcEJIcAJIr8JI70JJb0JJbsJJ7oJKLgJKrYJLLUJLbQJLrIJMLEJ" +
  "MbAJMq8JM64JNK0JNa0JNawJNqsJN6oJOKoJOKkJOagJOqkJOagJOqgJOqgJOqkJOagJOqcJO6YJPKYJPKcJO6YJPKYJPKYJ" +
  "PKYJPKcJO6gJOqYJPKUJPaQJPqQJPqMJP6QJPqMJP6MJP6MJP6MJP6YJPKQJPqIJQKIJQKIJQKIJQKIJQKIJQKIJQKIJQKIJ" +
  "QKEJQaEJQaEJQaAJQqAJQp8JQ58JQ50JRZsJR5oJSJkJSZgJSpgJSpgJSpcJS5cJS5cJS5cJS5cJS5cJS5UJAwFJmQlJmQlJ" +
  "mglImglImglImglImglImglIlQkEAkeUCQYCAwFCkQkICEGQCQoGQo8JDAVCkAkKBkKQCQoGQpAJCQdCkQkIAQEEQ5EJCwJE" +
  "kQlRkQlRkglQkwkEAkmUCQMCSZgJSpgJSowJBAhKiQkIAwEBTIcJCwFPhQkMAVCECV6CCWCCCWCBCWGCCWCBCWH+CGT+CGT8" +
  "CGb8CGb8CGb7CGf9CGX7CGf8CGb8CGb9CGX7CGf6CGj5CGn5CGn3CGv2CGz1CG31CG30CG7zCG/zCG/zCG/zCG/zCG/0CG70" +
  "CG7zCG/zCG/yCHDyCHDwCHLvCHPuCHTtCHXsCHfrCHnqCHrlCH7kCIAB4giCAeAIgwHfCIUB3AiHAdAIAwECBIoBzwgGA4sB" +
  "zwiUAc8IlQHOCJUBzAiYAcsImAHLCJgBygiZAckImwHHCJwBxgidAcUIngHACKMBvgimAbwIpwG6CKkBuAirAbYIrQG1CK4B" +
  "tAivAbQIrwGzCLABsgixAbEIsgGwCLMBrgi1Aa0ItgGsCLcBrAi3AasIuAGqCLkBqAi7AacIuwGmCL0BpQi+AaQIvwGiCMEB" +
  "oQjCAaEIwQGhCMIBnwjEAZ4IxQGdCMUBnAjHAZwIxwGbCMcBmwjIAZoIyQGZCMkBmQjKAZkIygGYCMoBmQjKAZcICAHCAZgI" +
  "BwHDAZcIzAGVCM0BlAjPAZMIzwGUCM8BkgjQAZEI0gGPCNQBjQjVAYwI1wGKCNgBigjYAYkI2gGICNoBiAjbAYcI3AGHCNsB" +
  "hwjcAYUI3QGFCN4BhAjeAYMI3wGDCOABggjgAYII4QGBCOEBgQjhAYEI4gGACOIBgQjhAYAI4wH/B+MB/gfkAf0H5gH8B+YB" +
  "+wfnAfoH6QH5B+kB+AfqAfgH6wH2B+wB9gfsAfYH7AH1B+0B9AfuAfQH7gH0B+4B9QftAfQH7gH0B+4B9AfuAfMH7wHzB+8B" +
  "8QfwAfEH8QHxB/EB8QfwAfEH8QHyB+8B8wfuAfMH7gH0B+0B9QfsAfYH6QH3B+kB+AfoAfoH5wH8B+IBgAgBAeABgwjfAYII" +
  "4gGACOMB/wfkAf4H5gH8B+YB/QfmAfwH5gH8B+YB/AfmAfkH6QH5B+kB9wcCAesB8gfxAfEH8gHzBwMC6gH5B+kB+gfpAfoH" +
  "5wH+B+QB/gffAQMB/gfgAYMI4AGDCOABggjgAYII4QGACOMBgQjhAYEI4gH6BwIF4gH4BwYD4QH3B+wB9QfuAfUH7QH1B+4B" +
  "9QfuAfUH7gH0B+8B8wfwAfEH8gHwB/IB7wf0Ae4H9QHtB/cB6wf3AewH9wHrB/gB6gf5AeoH+QHpB/oB6Qf6AecH/AEEAeIH" +
  "/AECBOAHgwLHBwECAROFAsEHBgMCEoYCyAcCEIkCvwcBAgEBBA6NAsIHBguQAsMHAgQCAZYCwgcBAp0CwwcPAY0CxQefAsEH" +
  "ogK/B6UCvQemArsHqQK5B6oCtwesArUHrgK0B68CsQeyArAHswKvB7MCqwe4AqcHvAKlB74CoAcDAb4CnQfGApsHyAKYB8oC" +
  "mAfLAogHAgMCAQUBzALTBgUDJATgAssGNAHjAqMGGgIIApkDmQbKA5MGzwOPBtQDyAMDvwLZA8YDBroC3APBAwMDBrYC3wO9" +
  "AxGwAuUDvAMRrQLpA7oDE6gC7gO5AxKmAvIDuAMTogL3A7YDE6AC/AOvAxedAoAEqwMbmQKFBKgDHZYCiQSlAx6UAosEowMg" +
  "kgKOBKADI48CkgSdAyUBA4gClgSUAzGGApkEkQMzgwKcBAEBjQM1gAKiBIoDNv8BpgQQBe4CO/wBqQQEBAMT4wI8+gHOBNQC" +
  "AQk9+AHSBM8CAgo99gHWBMwCBAMEAj31AdkEygJK9AHcBMcCS/IB4QTDAhoFLfEB5ATBAgYBEQoq7wHoBL8CBgEQDCnuAeoE" +
  "vwIBAQMCDQ8o7QHtBMECAQMLECfsAfEE3gIl7QHzBN0CJO0B9gTaAiTsAfkE1wIBASTrAfwE1AICASLsAf4E0QIlGgIDAQIB" +
  "ygGABc8CJhYDAgEDBQMEwQGCBc0CJxYDAhO8AYUFzAIDAyEWBAETuwGIBScFnQIDAiIWGboBigUiEpQCAwEiFhu4AYwFHhqD" +
  "AgUGDgEXFhy2AY8FHB73AQQECQImFwcCFLQBkAUaIvMBOhkGBBOyAZIFFybvARsBIRUJBQYCCrABlQUVKesBHwMdFAoRBq8B" +
  "lgUVK+YBIwYYFQkTBa4BmAUVK+UBJQQWGAgUBawBmAUWLeIBKAQRHAcVBqgBmQUYLRsFvwEsAg4fBhcFpwGZBQQGEC8QD7wB" +
  "LgUHIgYVB6YBmQUFCA4xDRK4ATIpAwEGDA+kAZwFBAoNMgoUtQE1LAUMD6QBoAUBCwUFATgBBAEVAgGwATYhBAYGCw+jAa4F" +
  "AwYBWagBPRwLAwQBAwgOowGuBQQsATakAT8aGgEIBgOiAbEFA2WhAUEZI6oBmwabAUcVJqkBngaZAUgTJ6gBoQaWAUsQEQoN" +
  "pgGlBpMBTQ8ODgylAacGiwFUDg4ODaQBqQaJAVUMDw4OowGsBoYBWgIVEAyhAbAGgwFyCgEEBAEIoAGyBoEBcAMEBAcGBaEB" +
  "tQZ+hQECA6QBtwZ8hwEBA6MBuQZ7iAEBCpoBvAZ5iQEBDJUBvwZ4iQEBDZMBwwZzmgGRAcYGBAFqnQGPAckGAwFnoAGNAcsG" +
  "AgFnoQGLAdEGZaIBfwEBAQIEAdQGAQMBBFmkAXwBCAEB4AZVpgEVAmQBBucGU6cBDwIBB2IBAwMB5wZPqQENBQMFUwIEAgIB" +
  "AwEBAwLqBkysAQoIBANSAgMDAQUDAgHtBkquAQEDAgwCA1AFAgIE9wZHwwECAzIDDAIDAgEBAQEBAwIBAQIC/AZCyAErAQQB" +
  "AQgKAgEDAgIBAwGGBz3NASoEAQoFEQMBBIMHOdABKBADAwUEAQYGhgc20wElGAIEAQwDhwcy1wElAQEYAwIBlQcv2gEiHAUC" +
  "AQEEjwcJAiPaASMcBAIIjwcECx3bASIeCaMHGt0BIxwHqAcX3QEkFQMGA6oHEuIBIxUEtAcP4wEjAwEPBrUHDeUBDgUTDwW3" +
  "BwvmAQwKDxAFuAcJ6AEKDQ4PBbkHB+kBCg4NDwW6BwICAeoBChALDAiqCQkSCwcLqgkKEgoGDKoJCBUJBQ6pCQcXCAQQqQkB" +
  "HQgCEcgJGcoJF8sJFs0JFM8JE88JEtEJEdEJEdAJE9EJEdIJDs8JAQYQ0QkBAQ/TCRDUCQsBAtQJCQQByAkBCwnOCQEIC84J" +
  "AQkL1wkLzQkBCgnaCQi5EwHvRAHhCQGlCQHizQEBAQEHAdkJAQMBnQkBQQWaCQE+AgEF3wkD3wkBAQGdVQLeCQbdCQjaCQrY" +
  "CQzWCQ3VCQ6HAwPKBhCFAwLLBhHGCQEJE84JFOUCAecGFfoCBcsGGMgJGckJGYADAcgGGf8CA8cGGf4CBcYGGfcCAgIJxQYZ" +
  "+AINxQYY+QINxAYZ+AIOwwYZ9wIQwgYa9QISwQYa9QITwQYa9AIUwAYZ8QICARa+BhrwAhu9BhnuAh+8BhnuAiC6BhntAiO4" +
  "BhruAiO4BhrvAiK2BhvuAgECAwQatQYb8QIBBxq1Bh3rAgELGrMGHvgCG7IGHfgCHA4CowYa+QIgCgOiBhr6AiIDAakGGfoC" +
  "JqoGGPkCJqsGGPkCJqsGF/kCJ6sGF/cCKasGFe8CAQooqwYV7gICCwEDI6sGFe4CAhAjqgYS8QIBEiKnBhXwAgETIqgGEvIC" +
  "ARMhqQYR8gICEwEBIKgGDvMCBBMBAx6pBgqTAxypBgeWAxysBgOYAxyqBgKaAxysBgGZAx2rBgGZAx3FCR3FCR63CQEBAQYB" +
  "BB3GCR3FCR3DCQEBEAcFxQkQBgEBBMcJD9MJDgUDzgkLAwEEAr8JAREFDgK6CQIkA94JBKwJAgoBFwK9CQEFAgECFAEVA7AJ" +
  "BSkE1AkCBQjTCQQCCsUJCAURvAkCBCG5CQIDJesGAc8CKrYJLAEB/QYDAQIBAa8CLAEB8wYBCQivAi30BgEJCK8CAgEs8gYB" +
  "CAqyAivxBgIFDLUCFgUQ7wYCBQu1AggCBAMFBgvHBgEsAgYKuQIBBQEHAwgK9AYCBwjIAgELB/YGAgkEuQICGwbxBgIDA9gC" +
  "AgkCAwHyBgfIAgEKAgIDCAH2BgnOAgoHAQMB9wYHzAIMCwH3BgbMAg2EBwTNAgEBC4QHBM4CC4UHBM8CCYEHAQQEzwIIhwcF" +
  "0gIDiAcEDwHEAgOIBwMPAuAJAuAJAuAJAskJARYBAgHKCQESAgMByAkCEQbHCQUPCcQJBg4MxAkDAQEMEcAJBQgBAxK9CQkK" +
  "E7wJCQEDBgkIAxIBqAkJAQYCCR4CpwkJAQYEAyMCmQIDiwcSCgEcBIgCAQIEmAcVAwQFARYDigIHlgcdBAIVAgEBiQIIlQcf" +
  "AgMTAosCDo8HIAIBAQMRAosCD48HIwICAQEMAQEB7AEBHw+OByQICQMB6wECHhGNBycBAQULAgGHAhOMBykCDwEB7AEBGhSM" +
  "BzzEAQElAxgbhgc+5gEGFh6EB0QLAdEBChQgggdIBwLPARINIYIHUs8BEwkkgQdSzgEYAij/BlXLAUX5BgEDVskBR/gGWwEB" +
  "xgFH9gZhwwFJ9AZmvgFL8gZuAQGgAQISTfMGbpgBBAMDEU7zBm6YAQsPUPIGbpcBDA5S8QZvfwIUEAlU8QZxewgOEgdY7wZz" +
  "eA8FFgNa7gZ2dYgB8AZ2awIFiQHyBnhmkQH0Bn1ekgH3Bn1bkwH3Bn4DAUsBB5cB9waEAUgCB5UB+AaGAUUIA5QB+QaHAT4B" +
  "AwoDkgH6BosBOg8BkwH5Bo0BOBACkQH6BpIBKAEJpAH6BpIBJwIIpQH7BpQBIgQFqAH7BpoBAwIFAQ8GAqwB+gaoAQa6AfoG" +
  "6AL7BuYC/AbmAvwG5gL8BucC+wbnAvoG6QL6BugC/AbrAvcG6gL4BuoCAgH2BucCAgL3BucCAgH5BugC+wbmAvwG5gL9BuUC" +
  "/gbjAoAH4gKBB+ACggffAoMH3wKDB98CgwffAoAH4QKBB+ECgwffAoQH3QKGB9wChwfbAogH2gKIB9oCiQfZAooH2QKKB9gC" +
  "igfYAosH1wKMB9YCjQfWAowH1wKMB9cCiwfYAosH1wKMB9YCjAfWAowH1gKMB9UCjgfTAo8H0wKQB9ECkgfQApAH0gKQB9IC" +
  "kQfRApEH0AKXB8sCmAfLApgHywKXB8oCmQfIApsHxwKbB8YCnQfFAp4HwwKgB8ICogfBAqEHwQKiB8ACogfBAqIHwQKjB8EC" +
  "oge/AqQHvwKkB78CpQe9AqYHvAKoB7gCqwe3AqwHtwKrB7YCrQe0Aq4HtAKvB7MCsAexArEHsQKyB7ACsgewArMHsAKyB7EC" +
  "sgexArEHsgKwB7ICsAedAgkNrweaAhAJrweZAhIBAQeuB5oCFAauB5oCFgKwB5oCFQOwBwUBlAITBbAHBQKTAhIEsgcGBI8C" +
  "FQIBAq4HAwiPAhYGpQcBBgMIjgIXBqQHAwMECAEBiwIYB6YHAgEHCIsCFwenBwMEAwiKAhgIpgcDDooCFwipBwQNiAIYB6sH" +
  "Aw6IAhgGqwcEDocCGwOrBwQPhgIbAqwHBAICDIUCyQcIDoICGAEDAa0HCgyBAhgIqgcLDIECGAerBwwOAwH8ARcIqQcNDgIC" +
  "+wEbBKoHDgwBAgEB+gHKBw4MAQMCAfcBygcQDAEE9gHMBxMM9wHMBxQM9AHPBxQJ9gHPBxUI9QHQBxUI9gHPBxUDAQP3Ac8H" +
  "FQH+Ac8HlALOB5QCzQeUAs4HlALOB5QCzweTAtAHkgLQB5IC0AeIAgIFAgHRB4gCAgPVB4kCAQPWB4QC3weDAuAHhQIQAcwH" +
  "hgINBAECyAeHAgwIxgeJAgsIwweMAgoKwwcCA4YCCQvDBwEGgwIKDMgHhgIJDMcHAQKEAgcMzAeDAgYCAgIEAQEBzAeDAt8H" +
  "gwIIAQEB1AeBAgkG0weAAgkH0geAAggI0geBAgYDAgHWB/8BBwLaB/sB5gf7AecH+gHpB/kB6wfLAQIFAQECIOwHzAEDAgIC" +
  "AQEBAgEb7QfMAQ4b7QfNAQMBCRvtB84BAgIDAwMZ7ge+AQEbARnvB70BAhMJFgUC6we8AQQPChcEBOoHvgEBDwsXAwXqB74B" +
  "ARANEwMBAQUCAuYHvAEICQ4RCgbmB7wBCAkRAgQGARLnB7sBCAggEecHvAEFAgYBIBLmB7wBBQIDBh4S5we7AQUBBAcOAQ0B" +
  "ARDoB7sBCggKAQIDCAEEAQIN6Ae6AQoICwECAwECDA7pB7gBCwoMBggT6AcFBK8BBQIGCA0FCQEBD+kHAQmtAQcCBgcNBA0L" +
  "9getAQcCBQUMAgIDDQz3B6sBCAIFBgkJDgn6B6UBAgQIAgQFCgoQBf0HpAEBBAkBBAINDQwG/QekAQIEBwQRDQEBCQj9B6IB" +
  "AwQHARUOBwIBCIAIngEEAw4BDRMECoAInQEJARoi/gefAQgCGyD9B6MBAgQdIPwHowECBh4FARf+B6ABAwchGv0HAgKaAQQI" +
  "IwwBC4EIfgIYBwECBR4PAgEBCIEIfgIZCQYbAQERAwaFCHwCGQMEAQYfEAMLgQh7AhgFCh8PBQmDCHkDGAQLHxECCYQIeQIJ" +
  "AQ8GAgIHHRADCIUIeQIJAg8KAQIDHhACB4kIdgQHAg8OAh4MAgIGAQECiQh3AwUDEAwEIAgEAgcDiAgMAWoGAgMQCQIBBSMC" +
  "DwSFCAEBDANrBxEJCCMCFAGGCAwEagcQCgcjAhQBhggMBGwEAwEMCwMDAcEICAdtCAoFAQYBxwgIB24HCgUBBQHICAoFcAYI" +
  "BAPPCAkEchEDAwHNCAcFbxMEAQHNCAYGAQFuEQfQCAIKaQICEQjfCGMGAREI3AgBAWUWCdwIaRMK3AhsDAEECgMB1AgBAmsN" +
  "AgILAgPRCHANAgIQ0QgBA2sPE9YIaQ8S2ghmDxLbCGYIAgYEAgvbCGYHBAYBBArcCGEBAQEDBwMFEN0IXxACBAIFCN8IYA8C" +
  "AwIFCOAIYA8FBgfhCGEOBAcH4QhgDgIBAgcH4QgTAgEBSA8CDAbhCAoCBQZFIAPjCAsBAQEDBgcBPCIB5AgIAgEDAwYFBQ4B" +
  "JgEFhgkHCAIHBAgJCR8CAokJBAECMB6MCQECAQICMR2MCQE5AQEayQkZAgHICRqoCQQbAgEYqAkCIQoCCswJBQkHzgkDCwPe" +
  "CQGpCQHhCQGO0AI=";

const COVERAGE_RLE =
  "ALGBCAHhCQHgCQLgCQLfCQPfCQPeCQTdCQXdCQXcCQbbCQfaCQjZCQnYCQrXCQvXCQvWCQzVCQ3UCQ7TCQ/SCRDRCRHQCRLP" +
  "CRPNCRXMCRbKCRjJCRnHCRvGCRzECR7DCR/DCR/CCSDCCSDCCSDCCSDCCSDBCSHBCSHBCSHBCSHBCSHBCSHBCSHBCSHBCSHB" +
  "CSHBCSHACSLACSK/CSO/CSO/CSO/CSO/CSO/CSO/CSO/CSO/CSO+CSS+CSS9CSW9CSW8CSa8CSa7CSe7CSe7CSe7CSe6CSi6" +
  "CSi6CSi5CSm5CSm4CSq4CSq3CSu3CSu2CSy2CSy1CS21CS20CS60CS61CS22CSy3CSu3CSu4CSq4CSq5CSm5CSm6CSi6CSi6" +
  "CSi6CSi6CSi6CSi6CSi6CSi6CSi5CSm5CSm5CSm5CSm5CSm4CSq4CSq3CSu3CSu2CSy2CSy1CS20CS6zCS+yCTCxCTGwCTKv" +
  "CTOvCTOuCTSuCTStCTWsCTarCTeqCTioCTqnCTulCT2jCT+hCUGfCUOdCUWZCUmWCUyWCUyVCU2VCU2UCU6UCU6TCU+TCU+S" +
  "CVCRCVGQCVKPCVOOCVSNCVWNCVWNCVWNCVWNCVWMCVaMCVaLCVeLCVeKCViKCViJCVmJCVmICVqICVqHCVuGCVyFCV2ECV6E" +
  "CV6DCV+DCV+CCWCBCWGBCWGACWKACWL/CGP+CGT+CGT9CGX8CGb8CGb8CGb8CGb7CGn5CGr3CG31CG7zCHDyCHHwCHTtCHbr" +
  "CHjpCHroCHvnCH3lCH7kCH/jCIAB4giBAeEIggHgCIMB3wiEAd0IhgHcCIcB2giJAdkIigHaCIkB2giJAdoIiQHaCIgB2wiI" +
  "AdoIiQHaCIkB2QiKAdkIigHYCIoB2QiKAdgIiwHXCIwB1giMAdYIjQHVCI4B1AiOAdQIjwHTCJAB0giQAdEIkgHQCJMBzgiU" +
  "Ac4IlQHMCJYBzAiXAcoImQHICJoBxwicAcUInQHDCKABwQihAb8IpAG8CKYBuwioAboIqAG6CKkBuQipAbgIqwG3CKsBtwis" +
  "AbYIrAG2CK0BtQitAbUIrgG0CK4BtAiuAbQIrwGzCK8BswivAbIIsQGxCLEBsAiyAbAIswGuCLQBrgi0Aa0ItgGsCLYBqwi3" +
  "AaoIuQGpCLkBqAi6AagIugGnCLsBpwi5AakItgGsCLQBrgiyAa8IsgGwCLABsgivAbIIrwGzCK4BswiuAbQIrgGzCK4BtAiu" +
  "AbMIrgG0CK4BtAitAbQIrgG1CK0BtQitAbUIrQG1CK0BtQitAbUIrQG1CK0BtQitAbUIrQG1CK4BtQitAbYIrQG2CKwBtwis" +
  "AbYIrAG3CKwBtgitAbYIrQG1CK4BtQitAbUIrQG1CK0BtQitAbYIrAG2CKwBtgisAbcIqwG3CKsBuAiqAbgIqgG5CKoBuAiq" +
  "AbgIqwG3CKsBtwisAbYIrAG2CK0BtQiuAbQIrgGzCLABsgixAbAIsgGwCLMBrgi1Aa0ItQGsCLcBqgi5AagIugGnCLwBpQi+" +
  "AaUIvgGkCL8BowjAAaIIwQGhCMEBoQjCAaAIwwGfCMQBngjFAZ0IxgGcCMcBmwjIAZoIyQGZCMoBlwjMAZYIzQGUCM8BkwjQ" +
  "AZEI0gGQCNMBjgjVAYwI2AGJCNoBhwjdAYMI4QGBCOEBgAjjAf4H5QH8B+cB+gfpAfcH7QH0B+8B8QfzAe0H9gHoB/wB3weE" +
  "AtwHhwLbB4cC2geJAtgHiwLWB40C1AeOAtIHkQLQB5MCzQeVAssHmALHB5sCxgedAsMHoALAB6ICvAenArkHqQK4B6sCtQet" +
  "ArMHsAKuB7QCngcCAQUBvALmBgIDHg/LAuEGLgHTArMGGgIIAooDqga5A6UGvgOhBsIDnQbGA5gGzAOSBtEDjQbXA4gG3AOD" +
  "BuED/wXkA/sF6AP3Be0D8wXwA/AF9APsBfgD6QX7A+UF/gPiBYIE3wWFBNsFiwTVBY8E0gWSBM8FlwQZAq4FoAQEBAMQpgW+" +
  "BKIFwgSfBcUEnAXJBJcFzASVBc8EkgXSBI4F1QSMBdgEiQXaBIcF2wSGBdwEhAXeBIMF3wSCBeAEgQXhBP8E5AT9BOUE/ATn" +
  "BPkE6QT4BOsE9gTsBPUE7gTPAgOgAvEEzAIHnQLzBMoCCpoC9QTHAg6WAvgExQIQlAL7BMICEpIC/QS/AhaPAoAFNwOCAhiM" +
  "AoQFNAb+ARuKAogFLwn7AR6IAo0FKQ0tB8IBIYcClQUeExcHAQQBErwBJIQCmQUZGg8luAEnggKeBRElAS60ASqAAqYFA1yy" +
  "ASz+AYgGrgEw+gGLBqsBM/gBjganATf1AZEGpQE58gGTBqMBPu0BlQahAUPoAZgGngFLAgfWAZsGnAFZ0QGeBpgBYgMEwgGg" +
  "BpYBa8ABowaTAW69AaYGkAFxugGqBowBdrUBrAaKAX6tAa8GhwGAAaoBswaEAYIBqAG4Bn+EAaYBvAZ7hwGjAcEGdokBoAHK" +
  "BgEBa40BnQHOBmmQAZkB0QZmlAGVAdUGYpgBjwHaBl+eAYQB4gZaqQEBA3bmBlaxAXToBlSyAXPrBlG0AXDuBk+1AW/xBky2" +
  "AW31Bki4AWz4BkW6AWv8Bj+8AWqEBwQDL78BaYwHLcABaI4HK8IBZ48HKcMBZ5EHJcYBZ5EHI8gBZhkB+QYfywFlEg/0BhvO" +
  "AWQOF/QGE9MBYwwb+QYCAgHcAWEKH9kIYAkh2gheByXaCFwGJ90IWAUp4wgBBEwEK+cISwQt5whKBC3nCEkEL+YISQQv5ghI" +
  "BDHmCEcEMeYIRgQz5ghEBTPmCEMGM+cIQQcz5whACDPoCD8IM+kIPQkz6gg8CTMDAQEBBwHdCDsJSNgIOQEBB0zVCEEBTdUI" +
  "jwHVCI4B1wiNAdUIjgHVCI4B1AiPAdQIjwHUCI4B1QiOAdUIjQHzBgLiAYwB6wYQ3AGLAecGGNoBigHkBhzaAT8BSOIGIdsB" +
  "PAcBAz3gBiXgATULPd8GKN8BNAs9IwO3BizdATQLPRwRrwYv2wE0Cz0YGaoGMdoBNAs9Fh2nBjTYATQLPQUBDiGkBjbXATQL" +
  "SgYjogY41gE0C3WeBjzUATMMdpwGPtQBMg12mQZB0wExDneXBkPTATAPd5UGRdIBLxB3lAZH0gEuEXeSBknRAS0Sd5IGSdIB" +
  "KxR3kAZL0gEpFnaQBkvTAScYdo4GTdMBJRp1jgZN1QEhHnONBk/VAR8gco0GT9cBGyRwjQZP2QEXKG6NBk/dAQ8va40GT+QB" +
  "AThpjQZPoQIRAVONBk+oAgEBAQhSjgZPswJSjgZPswJTjgZOswJUjQZOtAJUjQZNtAJVAwKHBk21AmCBBk20AmT9BU21AmX7" +
  "BU60Amf5BU61Amf4BU62Amj3BU23Amj1BU64Amj0BU64AmnyBU+4AmrxBU+4AmvwBU+4AmvwBU+4AmzvBVC3AmzvBVC3Am3u" +
  "BVC3Am3uBVC3Am7tBVC4Am3tBVC4Am3tBVC5AmztBVC5AmztBVC5AmztBVC5AmzuBU+4Am3uBU64Am7vBU24Am3wBU23Am7w" +
  "BU23Am3xBU22Am7xBUy3Am3yBUy2Am7yBUu3Am3zBUu3Amz0BUq4Amz0BUq4Amz0BUm5Am30BUi5Am30BUe6Am30BUa7Am70" +
  "BUW8Am30BUS9Am70BUK/Am30BUEkAZsCbfUFPx4PlQJs9QU9HBcLAwECAQH+AWz2BTsbGwIW+AFr9gU5Gzn1AWr3BTcbPPQB" +
  "a/YFNBtA8wFr9gUyG0LyAW31BS8PAQxF7wFv9QUsCg8ER+4BcPUFKQhf7QFx9QUnB2LsAXL1BSUGZesBcvcFIQdm6wFz9wUf" +
  "BmnqAXP5BRsHauoBdPoFFwhs6QF1/QUPC23qAXSEBgERb+kBdZUGb+oBdJQGcOoBdZMGceoBdJIGcuoBdZEGcusBdJAGc+wB" +
  "c5AGc+0BcpAGc+4BcZAGc+8BcJAGc/EBbpAGc/IBbZAGcvUBa5AGcvcBaJEGcfwBZJIGcIECXpMGbwYB+wFelAZ89QFclQaA" +
  "AfIBW5YGgQHxAVmXBoMB8AFXmQaDAfEBVJsGhAHtAVWdBoQB6gFVoAaEAdkBAQ5VowaEAdABDwVVpgaEAcsBa6oGgwHIAWyt" +
  "BoIBsAEBFGyzBg8DbagBDwxsuwYBCm2kARcGbMgGc5wBGwNrygZ3lgGKAcsGeZMBiQHNBnuPAYkBzwZ8jQGGAdMGfooBhQHV" +
  "Bn+IAYcB1AaAAYYBiQHTBoIBhAGKAdIGiQF8jAHRBo0BeI0B0AaPAXWPAdAGkAFxkgHPBpEBaZoBzQaUAWOfAcsGlgFgoQHK" +
  "BpgBXaQByAaaAVarAcYGnAFRsAHFBp0BTrIBxAaiAUe2AcMGpQE9vgHBBqoBNcMBwAatATDGAb4GsAEsyAG+BrIBKMsBvQa2" +
  "ASLNAb0GuAEa1AG8BrwBEtgBvAa/AQUBB9sBuwanA7sGpwO7BqcDuwanA7sGpwO7BqcDuwanA7sGpwO7BqYDvAamA70GpAO+" +
  "BqQDvwaiA8AGogPBBqADwgafA8QGngPFBp0DxgadA8UGngPEBp8DwwagA8MGnwPDBqADwgagA8IGoQPBBqEDwQaiA8AGogPA" +
  "BqIDwAaiA8AGogPBBqEDwQahA8IGoAPCBqADwwaeA8QGngPFBpwDxwabA8gGmQPJBpkDygaXA8sGlgPMBpUDzQaVA80GlAPO" +
  "BpQDzgaUA84GkwPPBpMD0AaSA9AGkwPQBpID0AaTA9AGkgPQBpMD0AaSA9EGkgPRBpED0gaQA9QGjgPUBo4D1QaNA9YGjAPX" +
  "BosD1waLA9gGigPZBokD2gaIA9oGiAPaBocD3AaGA9wGhQPdBoUD3QaFA90GhQPdBoUD3gaEA94GhAPfBoMD3waDA+AGggPg" +
  "BoED4gaAA+IGgQPiBoAD4waAA+MG/wLkBv4C5gb9AuYG/ALoBvoC6Qb5AuoG+ALrBvcC7Ab2Au0G9QLuBvQC7gb0Au8G8wLw" +
  "BvEC8gbwAvMG7wL0Bu0C9wbsAvcG6wL4BusC+AbqAvoG6QL6BugC+gbpAvgG6gL3BusC9gbsAvYG7AL1Bu0C9QbtAvQG7wLz" +
  "Bu8C8gbwAvIG8ALyBvAC8gbwAvIG8ALyBvAC8gbwAvIG8ALyBvAC8wbvAvMG7wL0Bu0C9QbtAvYG6wL3BusC9wbrAvcG6wL3" +
  "BusC9wbrAvcG6wL3BusC9wbrAvgG6QL5BukC+gbnAvsG5wL8BuUC/QblAv4G4wL/BuICgAfhAoEH4AKCB94ChAfdAoUH2wKH" +
  "B9kCiQfVAo4H0QKRB9ICkQfRApEH0gKQB9ICkAfTAo8H0wKPB9QCjgfUAo4H1AKOB9QCjgfUAo4H1AKPB9MCjwfTApAH0gKQ" +
  "B9ECkgfQApIHzwKUB84ClAfNApYHzAKXB8oCmQfJApoHxwKdB8QCnwfCAqEHwAKjB74CpAe9AqYHuwKnB7oCqQe4AqoHtgKt" +
  "B7QCrwezAq8HswKwB7ICsAeyArEHsQKxB7ECsgewArIHsAKzB68CswevArQHrgK0B64CtQetArYHqwK3B6sCuAepArkHqQK6" +
  "B6cCuweoArsHpwK7B6gCuwenArwHpwK8B6YCvQelAr8HowLAB6ICwgegAsQHngLIB5oCygeZAskHmQLKB5gCyweXAswHlgLN" +
  "B5UCzgeUAs8HkwLRB5EC0geQAtIHjwLUB44C1AeNAtYHjALWB4sC2AeKAtkHiALbB4YC3QeEAt4HgwLgB4AC4wf+AeQHyQEC" +
  "MecHyAEELeoHxwEIEAYP7wfFARACFAH3B8QBoAjBAaIIwAGkCL0BpQi9AaYIuwGoCLkBqgi4AasItwGtCLUBrgizAa8IswGv" +
  "CLIBsAiyAbAIsQGxCLEBsQiwAbMIrgG0CK0BtgirAbcIqQG6CKcBuwilAb4IowHACKABwwiDAQMXxgiAAQkPzAh9EQHUCHvp" +
  "CHjsCHXxCHD5CAECLQE2/wgqBTOBCScIMIQJJQssiAkhDyeMCR8UIJEJGx0DAw+XCRcsAaIJD9oJAeaMAQ==";

function decode(b64: string): Uint8Array {
  const bin = typeof atob === "function"
    ? atob(b64)
    : Buffer.from(b64, "base64").toString("binary");

  const cells = new Uint8Array(MASK_WIDTH * MASK_HEIGHT);
  let i = 0;   // cell cursor
  let p = 0;   // byte cursor
  let value = 0; // runs alternate, starting with water
  while (p < bin.length && i < cells.length) {
    let run = 0;
    let shift = 0;
    let byte: number;
    do {
      byte = bin.charCodeAt(p++);
      run |= (byte & 0x7f) << shift;
      shift += 7;
    } while (byte & 0x80);

    if (value) cells.fill(1, i, Math.min(i + run, cells.length));
    i += run;
    value ^= 1;
  }
  return cells;
}

// Decoded on first use rather than at module load: the server never asks
// isOnLand and the client never asks isCovered, so neither pays for both.
let landCells: Uint8Array | null = null;
let coverageCells: Uint8Array | null = null;

function at(cells: Uint8Array, lon: number, lat: number): boolean {
  const col = Math.floor((lon - MASK_BOUNDS.lonMin) / MASK_BOUNDS.res);
  const row = Math.floor((MASK_BOUNDS.latMax - lat) / MASK_BOUNDS.res);
  if (col < 0 || col >= MASK_WIDTH || row < 0 || row >= MASK_HEIGHT) return false;
  return cells[row * MASK_WIDTH + col] === 1;
}

/** True if (lon, lat) is land — the coastline the thermal overlay paints up to. */
export function isOnLand(lon: number, lat: number): boolean {
  if (!landCells) landCells = decode(LAND_RLE);
  return at(landCells, lon, lat);
}

/** True if (lon, lat) is land or within 0.2° of a coast — the server's fetch set. */
export function isCovered(lon: number, lat: number): boolean {
  if (!coverageCells) coverageCells = decode(COVERAGE_RLE);
  return at(coverageCells, lon, lat);
}
